// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9ixYHxT5dZHtzJxwpI1SjqQLYHsWedKo',
    appId: '1:549435465515:web:f0d5b26aa4418769a0ef6e',
    messagingSenderId: '549435465515',
    projectId: 'budi-timebank',
    authDomain: 'budi-timebank.firebaseapp.com',
    storageBucket: 'budi-timebank.appspot.com',
    measurementId: 'G-JV9H1Z08QC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG5UGwGtUYfLPnitqmPcgiliXoXK__yDI',
    appId: '1:549435465515:android:973b598a9c08390ca0ef6e',
    messagingSenderId: '549435465515',
    projectId: 'budi-timebank',
    storageBucket: 'budi-timebank.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZSP2ZTObaZM0noxPYKwHj0Tg2mRWJxgw',
    appId: '1:549435465515:ios:43ea1ea69030520da0ef6e',
    messagingSenderId: '549435465515',
    projectId: 'budi-timebank',
    storageBucket: 'budi-timebank.appspot.com',
    iosBundleId: 'com.example.testfyp',
  );
}
